# Generated by Django 5.0.4 on 2024-06-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=50)),
                ('emailid', models.EmailField(max_length=100)),
                ('qualification', models.CharField(choices=[('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('Diploma', 'Diploma')], default='Graduate', max_length=100)),
                ('subject', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics & Communications', 'Electronics & Communications'), ('Electrical & Electronics', 'Electrical & Electronics'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Chemical', 'Chemical'), ('Physics', 'Physics'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('English', 'English'), ('Hindi', 'Hindi'), ('Economics', 'Economics'), ('Commerce', 'Commerce'), ('History', 'History'), ('Geography', 'Geography'), ('Political Science', 'Political Science'), ('Sociology', 'Sociology'), ('Psychology', 'Psychology'), ('Botany', 'Botany'), ('Zoology', 'Zoology'), ('Microbiology', 'Microbiology'), ('Biochemistry', 'Biochemistry'), ('Biotechnology', 'Biotechnology'), ('Agriculture', 'Agriculture'), ('Home Science', 'Home Science'), ('Physical Education', 'Physical Education'), ('Sports', 'Sports'), ('Music', 'Music'), ('Fine Arts', 'Fine Arts'), ('Dance', 'Dance'), ('Arts', 'Arts'), ('Law', 'Law'), ('Journalism', 'Journalism'), ('Library Science', 'Library Science')], max_length=200)),
            ],
        ),
    ]
