# Generated by Django 5.0.4 on 2024-06-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_faculty_verification_alter_faculty_emailid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
