# Generated by Django 5.0.4 on 2024-07-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_faculty_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
