# Generated by Django 5.0.4 on 2024-07-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_faculty_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
