# Generated by Django 5.0.4 on 2024-07-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_faculty_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='subject',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics & Communications', 'Electronics & Communications'), ('Electrical & Electronics', 'Electrical & Electronics'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Chemical', 'Chemical'), ('Physics', 'Physics'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('English', 'English'), ('Hindi', 'Hindi'), ('Economics', 'Economics'), ('Commerce', 'Commerce'), ('History', 'History'), ('Geography', 'Geography'), ('Political Science', 'Political Science'), ('Sociology', 'Sociology'), ('Psychology', 'Psychology'), ('Botany', 'Botany'), ('Zoology', 'Zoology'), ('Microbiology', 'Microbiology'), ('Biochemistry', 'Biochemistry'), ('Biotechnology', 'Biotechnology'), ('Agriculture', 'Agriculture'), ('Home Science', 'Home Science'), ('Physical Education', 'Physical Education'), ('Sports', 'Sports'), ('Music', 'Music'), ('Fine Arts', 'Fine Arts'), ('Dance', 'Dance'), ('Arts', 'Arts'), ('Law', 'Law'), ('Journalism', 'Journalism'), ('Library Science', 'Library Science')], default='subject', max_length=200),
        ),
    ]
