# Generated by Django 5.0.4 on 2024-08-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_faculty_options_alter_faculty_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodule',
            name='module_desc',
        ),
    ]
