# Generated by Django 5.0.4 on 2024-08-28 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_coursemodule_module_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='videos/')),
                ('course_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coursemodule')),
            ],
        ),
    ]
