# Generated by Django 5.0.4 on 2024-10-23 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_enrolled',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.course'),
        ),
    ]
